import { Product, Category } from '@/types';

export const demoCategories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', icon: '💻' },
  { id: '2', name: 'Clothing', slug: 'clothing', icon: '👕' },
  { id: '3', name: 'Home & Garden', slug: 'home-garden', icon: '🏡' },
  { id: '4', name: 'Sports', slug: 'sports', icon: '⚽' },
  { id: '5', name: 'Books', slug: 'books', icon: '📚' },
  { id: '6', name: 'Beauty', slug: 'beauty', icon: '💄' },
];

export const demoProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio. Perfect for music lovers and professionals alike.',
    price: 299.99,
    image: '',
    category: 'Electronics',
    rating: 4.8,
    reviews_count: 1243,
    in_stock: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    description: 'Advanced fitness tracking, heart rate monitoring, GPS, and seamless smartphone integration. Water-resistant up to 50 meters.',
    price: 399.99,
    image: '',
    category: 'Electronics',
    rating: 4.6,
    reviews_count: 892,
    in_stock: true,
    created_at: '2024-01-14T00:00:00Z',
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft, breathable organic cotton t-shirt. Available in multiple colors. Ethically sourced and sustainably produced.',
    price: 34.99,
    image: '',
    category: 'Clothing',
    rating: 4.5,
    reviews_count: 567,
    in_stock: true,
    created_at: '2024-01-13T00:00:00Z',
  },
  {
    id: '4',
    name: 'Minimalist Desk Lamp',
    description: 'Modern LED desk lamp with adjustable brightness and color temperature. USB charging port included. Perfect for your home office.',
    price: 79.99,
    image: '',
    category: 'Home & Garden',
    rating: 4.7,
    reviews_count: 334,
    in_stock: true,
    created_at: '2024-01-12T00:00:00Z',
  },
  {
    id: '5',
    name: 'Yoga Mat Premium',
    description: 'Extra-thick, non-slip yoga mat made from eco-friendly materials. Includes carrying strap and alignment markers.',
    price: 49.99,
    image: '',
    category: 'Sports',
    rating: 4.9,
    reviews_count: 1567,
    in_stock: true,
    created_at: '2024-01-11T00:00:00Z',
  },
  {
    id: '6',
    name: 'Bestseller Novel Collection',
    description: 'Curated collection of 5 bestselling novels from award-winning authors. Beautiful hardcover editions with dust jackets.',
    price: 59.99,
    image: '',
    category: 'Books',
    rating: 4.4,
    reviews_count: 223,
    in_stock: true,
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: '7',
    name: 'Luxury Skincare Set',
    description: 'Complete skincare routine with cleanser, toner, serum, moisturizer, and SPF. Made with natural ingredients.',
    price: 129.99,
    image: '',
    category: 'Beauty',
    rating: 4.7,
    reviews_count: 445,
    in_stock: true,
    created_at: '2024-01-09T00:00:00Z',
  },
  {
    id: '8',
    name: 'Bluetooth Portable Speaker',
    description: 'Compact waterproof speaker with 360-degree sound, 20-hour battery, and built-in microphone for hands-free calls.',
    price: 89.99,
    image: '',
    category: 'Electronics',
    rating: 4.5,
    reviews_count: 778,
    in_stock: true,
    created_at: '2024-01-08T00:00:00Z',
  },
  {
    id: '9',
    name: 'Denim Jacket Classic',
    description: 'Timeless denim jacket with a modern fit. Premium Japanese selvedge denim. Versatile for any season.',
    price: 119.99,
    image: '',
    category: 'Clothing',
    rating: 4.6,
    reviews_count: 389,
    in_stock: true,
    created_at: '2024-01-07T00:00:00Z',
  },
  {
    id: '10',
    name: 'Indoor Plant Set',
    description: 'Collection of 3 easy-care indoor plants in decorative ceramic pots. Includes care guide and plant food.',
    price: 64.99,
    image: '',
    category: 'Home & Garden',
    rating: 4.3,
    reviews_count: 198,
    in_stock: true,
    created_at: '2024-01-06T00:00:00Z',
  },
  {
    id: '11',
    name: 'Running Shoes Ultra',
    description: 'Lightweight, responsive running shoes with advanced cushioning technology. Breathable mesh upper and durable outsole.',
    price: 159.99,
    image: '',
    category: 'Sports',
    rating: 4.8,
    reviews_count: 923,
    in_stock: true,
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: '12',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator. Includes USB-C cable.',
    price: 29.99,
    image: '',
    category: 'Electronics',
    rating: 4.4,
    reviews_count: 654,
    in_stock: true,
    created_at: '2024-01-04T00:00:00Z',
  },
];
